# Site settings
title: Asad Mirza
description: A site to catalog my work.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amirza.dev" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Asad Mirza
user_description: My work primarily deals with computational fluid dynamics (CFD), finite element analysis (FEA), 3D computer aided design (CAD), as well as Python and MATLAB programming.
user_title: PhD Candidate - Biomedical Engineering
email: asadmirza33165@gmail.com
# twitter_username: lorem_ipsum
github_username:  DThornz
# gplus_username:  lorem_ipsum
# Google Analytics
google_analytics: G-91CC5KCBCK

exclude: ['package.json', 'src' , 'node_modules']
